### ISSUE TITLE
Typo in td_kernel_pmvw.py?

### ISSUE THREAD

**Issue by ernOho** [smueller18/TDKernelDMVW#1]
Hi!
I was planning to implement your code for a project(thanks for the contribution!). Currently I am going through your code and I saw that you defined the confidence_map alpha as followed: 

self.confidence_map = 1 - np.exp(-self.importance_weight_map / (self.sigma_omega * self.sigma_omega)) [td_kernel_dmvw.py, 171]

however in Achim J. Lilienthal's approach the importance_weight_map is squared

self.confidence_map = 1 - np.exp(-(self.importance_weight_map)**2 / (self.sigma_omega * self.sigma_omega)).

Has the importance_weight_map been squared somewhere else in the script for efficiency reasons or is this a typo?

with kind regards,
and thanks again

**Comment by smueller18** [comment]
Hi @ernOho,

> Has the importance_weight_map been squared somewhere else in the script for efficiency reasons or is this a typo?

It is neither a typo nor is it squared at another line of code. Both implementations are correct. The equation in `A. J. Lilienthal, M. Reggente, M. Trincavelli, J. L. Blanco and J. Gonzalez, "A statistical approach to gas distribution modelling with mobile robots - The Kernel DM+V algorithm,"` uses the squared importance weight map while the other equation in `M. Reggente and A. J. Lilienthal, "Using local wind information for gas distribution mapping in outdoor environments with a mobile robot"` uses the non-squared weight map.

Its quite a long time ago when I studied this algorithms. But I slightly remember that I was also a little confused. If you check the papers, than you can see that the non-squared confidence weight map is preferred when using the wind component.

**Comment by smueller18** [comment]
closed by #2
